---
- name: Create Overleaf Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ overleaf_config_directory }}"

- name: Create Overleaf network
  docker_network:
    name: overleaf
    driver_options:
      com.docker.network.bridge.name: overleaf

- name: mongo
  docker_container:
    name: mongo
    image: mongo
    pull: true
    volumes:
      - "{{ overleaf_config_directory }}/mongo:/data/db"
    ports:
      - "27017:27017"
    restart_policy: unless-stopped
    networks:
      - name: overleaf

- name: redis
  docker_container:
    name: redis
    image: redis:5
    pull: true
    volumes:
      - "{{ overleaf_config_directory }}/redis:/data/db"
    ports:
      - "6379:6379"
    restart_policy: unless-stopped
    networks:
      - name: overleaf

- name: overleaf
  docker_container:
    name: overleaf
    # image: sharelatex/sharelatex
    image: tuetenk0pp/sharelatex-full
    pull: true
    volumes:
      - "{{ overleaf_config_directory }}/sharelatex:/var/lib/sharelatex"
    ports:
      - "{{ overleaf_port }}:80"
    env:
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: "url,project_file"

      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: "true"

      # Disables email confirmation requirement
      EMAIL_CONFIRMATION_DISABLED: "true"

      # temporary fix for LuaLaTex compiles
      # see https://github.com/overleaf/overleaf/issues/695
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
    restart_policy: unless-stopped
    memory: "{{ overleaf_memory }}"
    networks:
      - name: overleaf
    labels:
      traefik.enable: "{{ overleaf_available_externally | string }}"
      traefik.http.routers.overleaf.rule: "Host(`{{ overleaf_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.overleaf.tls.certresolver: "letsencrypt"
      traefik.http.routers.overleaf.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.overleaf.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.overleaf.loadbalancer.server.port: "80"
