---
- name: VSCode Docker Container
  docker_container:
    name: vscode_server
    image: codercom/code-server
    pull: true
    volumes:
      - "{{ vscode_config_directory }}:/home/coder/.config"
      - "{{ vscode_projects_directory }}:/home/coder/project"
    ports:
      - "{{ vscode_port }}:8080"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      USER: "{{ ansible_nas_user }}"
    restart_policy: unless-stopped
    memory: "{{ vscode_memory }}"
    labels:
      traefik.enable: "{{ vscode_available_externally | string }}"
      traefik.http.routers.vscode.rule: "Host(`{{ vscode_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.vscode.tls.certresolver: "letsencrypt"
      traefik.http.routers.vscode.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.vscode.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.vscode.loadbalancer.server.port: "8080"
