- name: Create Flaresolverr Docker Container
  docker_container:
    name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    pull: true
    env:
      LOG_LEVEL: "info"
      LOG_HTML: "false"
      CAPTCHA_SOLVER: "none"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ flaresolverr_port }}:8191"
    restart_policy: unless-stopped
    memory: "{{ flaresolverr_memory }}"
    labels:
      traefik.enable: "{{ flaresolverr_available_externally }}"
      traefik.http.routers.flaresolverr.rule: "Host(`{{ flaresolverr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.flaresolverr.tls.certresolver: "letsencrypt"
      traefik.http.routers.flaresolverr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.flaresolverr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.flaresolverr.loadbalancer.server.port: "{{ flaresolverr_port }}"
