---
- name: Start flaresolverr
  block:
    - name: Create flaresolverr Docker Container
      docker_container:
        name: "{{ flaresolverr_container_name }}"
        image: ghcr.io/flaresolverr/flaresolverr
        pull: true
        env:
          LOG_LEVEL: "info"
          LOG_HTML: "false"
          CAPTCHA_SOLVER: "none"
          TZ: "{{ ansible_nas_timezone }}"
        ports:
          - "{{ flaresolverr_port }}:8191"
        restart_policy: unless-stopped
        memory: "{{ flaresolverr_memory }}"
  when: flaresolverr_enabled is true

- name: Stop flaresolverr
  block:
    - name: Stop flaresolverr
      docker_container:
        name: "{{ flaresolverr_container_name }}"
        state: absent
  when: flaresolverr_enabled is false
