---
- name: Create Prowlarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prowlarr_data_directory }}"

- name: prowlarr
  docker_container:
    name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:develop
    pull: true
    volumes:
      - "{{ prowlarr_data_directory }}:/config:rw"
    ports:
      - "{{ prowlarr_port }}:9696"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ prowlarr_user_id }}"
      PGID: "{{ prowlarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ prowlarr_memory }}"
    recreate: true
    labels:
      traefik.enable: "{{ prowlarr_available_externally | string }}"
      traefik.http.routers.prowlarr.rule: "Host(`{{ prowlarr_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.prowlarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.prowlarr.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.prowlarr.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
      com.centurylinklabs.watchtower.enable: "{{ (watchtower_enabled and watchtower_label_enable) | ternary(prowlarr_watchtower_update_enabled, omit) | string }}"
